DROP DATABASE IF EXISTS book_db;

CREATE DATABASE book_db;

USE book_db;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS books;
CREATE TABLE books (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name TEXT NULL,
created_at DATETIME,
);